### ISSUE TITLE
&zwnj; displaying as text

### ISSUE THREAD

**Issue by khornberg** [btecu/ember-cli-bootstrap-datetimepicker#9] opened 2016-06-07 14:12 UTC
Using the latest version the default `&zwnj;` is displaying as text rather than being interrepted.

![image](https://cloud.githubusercontent.com/assets/3442051/15860731/db0f7bb4-2c8f-11e6-923d-92162a46cca4.png)

Setting `iconText` to a blank string fixes it.
![image](https://cloud.githubusercontent.com/assets/3442051/15860704/bd888f22-2c8f-11e6-9bd4-e34ec57a1dbb.png)

Is that the intent?

**Comment by btecu** [comment] 2016-06-07 21:34
No, that's not the intent.
I wonder if just having `<i class={{iconClasses}}>{{iconText}}</i>` on one line instead of 
```
<i class={{iconClasses}}>
  {{iconText}}
</i>
```
with new lines, fixes the issue. Can you test that? Otherwise, I'll just change the default to empty string.

**Comment by btecu** [comment] 2016-06-08 15:36
I'm not able to reproduce this. Do you have a repo demonstrating the issue?

**Comment by btecu** [comment] 2016-06-08 15:43
Fixed in `0.1.5`.

**Closed by btecu** 2016-06-08 15:43 UTC

**Comment by khornberg** [comment] 2016-06-09 12:36
Yes. The default string seems to work fine. Another option is to use triple curly brackets `{{{raw_html}}}`. I like the implementation as it.
